### ISSUE TITLE
Search finds just one occurence

### ISSUE THREAD

**Issue by ondrosik** [Accessiware/VisCon#1]
When searching for a specific phrase, Viscon in my case finds only the first occurence. Steps to reproduce:

Create a simple document, like this

red
blue
green
yellow
-----------
red
green
yellow
blue

1) I go to the top of a document. I press ctrl+f, type yellow and press enter. Curor moves to first occurence of yellow. That's OK.
2) Now I press ctrl+f and enter, I expect to move to the next yellov. It doesn't work, even if i move the currosr a littlebit to the ------ section
3) F3 behaves the same, cursor still moves to the first occurence of yellov. You can press F3 manytimes normal behavior will be to jump to second one and then find nothing. Now it moves still to the first one.

**Comment by NicklasTegner** [comment]
hi

thanks for this report.
this issue has been fixed in the next version of VisCon
