### ISSUE TITLE
Runtime Issue loading app Executable on Win10 64-bit

### ISSUE THREAD

**Issue by njsch** [Accessiware/VisCon#3]
I am running into an issue where the first time I run the program after installing, it tries to download an update, then the program doesn't load.  The next time I try to load it from either the desktop or start menu, I get an error saying that the program cannot be located.

using a HP Probook running Win10 v2004 (x86_64) with JAWS 2021.2102.34 and NVDA 2020.1.

**Comment by NicklasTegner** [comment]
Hi @njsch 

It seems that on some pc, Windows Secure (Windows Defender) removes the exe due to it not being signed.

To fix this, you could add an exclusion in Windows Firewall that points to the installation folder of isCon (default C:/Program Files (x86)/accessiware/VisCon/ )

**Comment by njsch** [comment]
@NicklasTegner, I don't use Windows defender but I do use another solution so I should've checked that one. I'll let you know what happens.￼

**Comment by NicklasTegner** [comment]
Since I haven't gotten a reply, I'll mark this issues as closed.
Feel free to reopen or create a new issue, if you encounter this problem again.
